eureka:
  server:
    enable-self-preservation: true
    wait-time-in-ms-when-sync-empty: 5000
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
 
#security:
#  basic:
#    enabled: true
#  user:
#    name: eureka
#    password: khTUcUUQ33WkJGC
#    role: SYSTEM
    
logging:  
#  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'
