turbine:
  cluster-name-expression: "'default'"
  app-config: MICROSERVICE,MICROSERVICE-OAUTH2
  combine-host-port: true

security:
  basic:
    enabled: false
  user:
    name: turbine
    password: CYVTJdEtAcCxyJe
    role: ROLE_ADMIN
  
logging:  
#  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud.netflix: 'DEBUG'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'
