turbine:
  clusterNameExpression: "'default'"
  appConfig: MICROSERVICE,MICROSERVICE-OAUTH2
  combineHostPort: true

security:
  basic:
    enabled: true
  user:
    name: turbine
    password: CYVTJdEtAcCxyJe
    role: SYSTEM
  
logging:  
#  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud.netflix: 'DEBUG'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'
