spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.0.2:5432/srdescuento-db
    username: srdescuento
    password: YPW4xw8qyNqskRp
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update



eureka:
  instance:
    metadata-map:
      management:
        port: 9090
