  data:
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      
      
config:
  environment: devel
  # environment: qa
  # environment: produc
  queue:
    exchange: exchange
    queue: primary
    queue-consulta-planespago-sifco-endpoint: queue-planes-pago
    routingkey: routingkey   

eureka:
  instance:
    metadata-map:
      management:
        port: 9090
